name: CI

on:
  push:
    branches: [ "main" , "remove-m4"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: sudo apt-get install -y guile-3.0-dev libtree-sitter-dev
    - name: setenv
      run: export LANG=C.UTF-8 TERM=dumb VERBOSE=true GUILE_AUTO_COMPILE=0
    - name: bootstrap
      run: ./bootstrap

    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make -j
      
    - name: Run check
      run: make check -j
      
    - name: Run distcheck
      run: make distcheck -j
