name: CI

on:
  push:
    branches: [ "main", "ci-test"]
  pull_request:
    branches: [ "main" ]

jobs:
  guix-build:

    runs-on: ubuntu-latest

    steps:

    - name: Guix cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/guix
        # use a key that (almost) never matches
        key: guix-cache-
        restore-keys: |
          guix-cache-
    - name: Install Guix
      id: install-guix
      uses: PromyLOPh/guix-install-action@v1

    - uses: actions/checkout@v3
    - name: build
      run: guix build -f guix.scm